### PR TITLE
Unified grammar in effects to third person

### PR DESCRIPTION
**Pull request by vooku**
It is better for bots etc.

### CODE REVIEW

**Comment by bukinoshita** [comment]
Thank you! 🎉

**Comment by vooku** [comment]
btw do you mind publishing it to npm? We're using it and I would appreciate the change :octocat:

**Comment by bukinoshita** [comment]
Hi @vooku, just released [`v0.0.3`](https://github.com/bukinoshita/harry-potter-spells/releases/tag/0.0.3).

Can you tell more about how you're using it? I'm just curious haha 😅

**Comment by vooku** [comment]
Thanks! We have a slack standup bot stylized as Hermione, she recommends a spell every day 🤣

**Pull request merged**
